# Generated by Django 4.1.5 on 2023-01-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220822_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Картинка для привлечения внимания', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
